services:
  crafty:
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      TZ: Etc/UTC
    group_add:
      - 568
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    platform: linux/amd64
    ports:
      - '8443:8443'
      - '8123:8123'
      - 19132:19132/udp
      - 25500-25600:25500-25600
    privileged: False
    pull_policy: missing
    restart: 'no'
    stdin_open: False
    tty: False
    volumes:
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/main/apps/crafty/app/config
        target: /crafty/app/config
        type: bind
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/main/apps/crafty/backups
        target: /crafty/backups
        type: bind
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/main/apps/crafty/import
        target: /crafty/import
        type: bind
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/main/apps/crafty/logs
        target: /crafty/logs
        type: bind
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/main/apps/crafty/servers
        target: /crafty/servers
        type: bind
volumes: {}
x-notes: >+
  # iX App


  ## Bug Reports and Feature Requests


  If you find a bug in this app or have an idea for a new feature, please file
  an issue at

  https://github.com/truenas/apps

x-portals:
  - host: 0.0.0.0
    name: Web UI
    path: /panel
    port: 8443
    scheme: https
