# ---- Plugins ----

[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.yazi]
animation = "fromTop"
command = "uwsm-app -- ghostty --class=com.pypr-yazi -e yazi"
class = "com.pypr-yazi"
size = "75% 70%"
max_size = "2560px 100%"
margin = 170

[scratchpads.obsidian]
animation = "fromTop"
command = "uwsm-app obsidian"
class = "obsidian"
size = "75% 75%"
max_size = "2560px 100%"
margin = 170
