# ---- Plugins ----

[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.obsidian]
animation = "fromTop"
command = "uwsm-app obsidian"
class = "obsidian"
size = "75% 75%"
max_size = "2560px 100%"
margin = 170
